UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-01-16', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-01-02' AND company_id=1 AND kam_id=3 AND kunde='Gerresheimer Tettau GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-02-11', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-01-28' AND company_id=1 AND kam_id=4 AND kunde='robatherm GmbH & Co. KG';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-02-14', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-01-30' AND company_id=1 AND kam_id=3 AND kunde='Thomas Scherz Dental Keramik GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-02-17', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-02-03' AND company_id=1 AND kam_id=5 AND kunde='IZOBLOK GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-02-18', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-02-04' AND company_id=1 AND kam_id=3 AND kunde='apikal Anlagenbau GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-03-10', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-02-24' AND company_id=1 AND kam_id=4 AND kunde='VTA Software & Service GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-03-10', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-02-24' AND company_id=1 AND kam_id=4 AND kunde='Axians Rhön-Montage GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-03-19', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-03-05' AND company_id=1 AND kam_id=5 AND kunde='Sozialwerk Heuser Heimbetriebsgesellschaft für Nordrhein-Westfalen mbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-03-20', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-03-06' AND company_id=1 AND kam_id=3 AND kunde='Audio Design Lautsprecher Vertriebs GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-03-25', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-03-11' AND company_id=1 AND kam_id=5 AND kunde='Landhaus-Bau Glinstedt GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-03-29', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-03-15' AND company_id=1 AND kam_id=3 AND kunde='K&P Kälte Klima GbR';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-04-04', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-03-21' AND company_id=1 AND kam_id=4 AND kunde='HKA Häusliche Kranken- und Altenpflege GmbH & Co. KG';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-04-08', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-03-25' AND company_id=1 AND kam_id=5 AND kunde='GM Getränketechnik & Maschinenbau GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-04-11', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-03-28' AND company_id=1 AND kam_id=4 AND kunde='Kanadevia Inova BioMethan GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-04-15', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-01' AND company_id=1 AND kam_id=8 AND kunde='Diakoniestation am Ev. Krankenhaus Lippstadt gGmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-04-18', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-04' AND company_id=1 AND kam_id=8 AND kunde='Jogerst Stein Technologie GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-04-22', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-08' AND company_id=1 AND kam_id=8 AND kunde='Marienstift Dorfen';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-04-22', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-08' AND company_id=1 AND kam_id=8 AND kunde='Peter und Lochner Beratende Ingenieure für Bauwesen GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-04-24', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-10' AND company_id=1 AND kam_id=4 AND kunde='NEUHAUSER GmbH & Co. KG';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-02', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-18' AND company_id=1 AND kam_id=8 AND kunde='H+E Haustechnik und Elektro GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-02', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-18' AND company_id=1 AND kam_id=7 AND kunde='AMS Brendel GmbH Steuerberatungsgesellschaft';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-03', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-19' AND company_id=1 AND kam_id=8 AND kunde='H&H Gerätebau GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-08', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-22' AND company_id=1 AND kam_id=4 AND kunde='ASTRAL business intelligence services GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-07', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-23' AND company_id=1 AND kam_id=8 AND kunde='Karl Hartinger Kranbetrieb GmbH + Co. KG';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-12', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-28' AND company_id=1 AND kam_id=8 AND kunde='Wartig Nord GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-12', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-28' AND company_id=1 AND kam_id=8 AND kunde='Autohaus Wolfrum GmbH Naila';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-13', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-04-29' AND company_id=1 AND kam_id=33 AND kunde='Bruno Brenner, Garten- und Landschaftsbau GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-19', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-05-05' AND company_id=1 AND kam_id=33 AND kunde='BALTIC Taucherei- und Bergungsbetrieb Rostock GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-20', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-05-06' AND company_id=1 AND kam_id=8 AND kunde='Vaventus AG Kälte Klima Lüftung/ Lorenz GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-20', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-05-06' AND company_id=1 AND kam_id=4 AND kunde='BSU Sanierungsunion Berlin GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-24', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-05-10' AND company_id=1 AND kam_id=8 AND kunde='Peter Krüger Sanitär- und Heizungstechnik';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-27', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-05-13' AND company_id=1 AND kam_id=8 AND kunde='x-tention Informationstechnologie GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-05-30', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-05-16' AND company_id=1 AND kam_id=4 AND kunde='M. Kratzer Sanitär Heizung Spenglerei GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-06-06', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-05-23' AND company_id=1 AND kam_id=4 AND kunde='Scheuten Glastechnik Heiden GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-06-13', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-05-30' AND company_id=1 AND kam_id=7 AND kunde='Energieversorgung Main-Spessart GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-06-16', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-06-01' AND company_id=1 AND kam_id=8 AND kunde='Diakoniestation am Ev. Krankenhaus Lippstadt gGmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-06-15', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-06-01' AND company_id=1 AND kam_id=8 AND kunde='Logatec GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-06-17', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-06-03' AND company_id=1 AND kam_id=4 AND kunde='KST-Motorenversuch GmbH & Co. KG';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-06-20', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-06-06' AND company_id=1 AND kam_id=8 AND kunde='Trans-Service GmbH Schwarzenberg';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-06-22', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-06-08' AND company_id=1 AND kam_id=8 AND kunde='Physiotraining Ruwertal GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-07-12', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-06-21' AND company_id=1 AND kam_id=8 AND kunde='Wartig Nord GmbH';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-08-26', neuer_ap_intern = 'Vertrieb' WHERE datum='2026-06-26' AND company_id=1 AND kam_id=4 AND kunde='Diakoneo';
UPDATE deals_vl SET status = 'Verloren', ae_wert = 0.0, weitergeben_an_vertrieb = 'Ja', auslaufend_am = '2026-07-12', gekuendigt_am = '2026-06-12', ansprechpartner = 'Max Mustermann', telefon = '01771234567', email_kontakt = 'max@highoffice.com', terminiert = 1, neuer_ap_intern = 'Vertrieb' WHERE datum='2026-06-28' AND company_id=1 AND kam_id=4 AND kunde='MKG GÖBEL Solutions GmbH';
INSERT INTO upsale_deals (deals_vl_id, angebotsdatum, angebotsvolumen, status)
  SELECT vl.id, '2026-06-15', 10000.0, 'Offen'
  FROM deals_vl vl
  WHERE vl.datum='2026-06-28' AND vl.company_id=1 AND vl.kam_id=4 AND vl.kunde='MKG GÖBEL Solutions GmbH'
    AND NOT EXISTS (SELECT 1 FROM upsale_deals ud WHERE ud.deals_vl_id = vl.id)
  LIMIT 1
