-- Migration 043: Mitarbeiternamen + Kündigungen-Kontaktdaten synchronisieren

-- Mitarbeiternamen
UPDATE employees SET name='René', rolle='NKV-Closer', standort=NULL WHERE id=1;
UPDATE employees SET name='Deniz Akpinar', rolle='Multi', standort='Bonn' WHERE id=2;
UPDATE employees SET name='Timo', rolle='Multi', standort='Braunschweig' WHERE id=3;
UPDATE employees SET name='Rene Friedl', rolle='KAM', standort='Bonn' WHERE id=4;
UPDATE employees SET name='Albert', rolle='Multi', standort='Bonn' WHERE id=5;
UPDATE employees SET name='Daniel Adams', rolle='KAM', standort='Braunschweig' WHERE id=6;
UPDATE employees SET name='Joshua Arendt', rolle='KAM', standort='Braunschweig' WHERE id=7;
UPDATE employees SET name='Sergio Verlardo', rolle='KAM', standort='Braunschweig' WHERE id=8;
UPDATE employees SET name='Tobias Böttcher', rolle='Multi', standort='Bonn' WHERE id=9;
UPDATE employees SET name='Mikail Kotaman', rolle='Multi', standort='Bonn' WHERE id=10;
UPDATE employees SET name='Clemens Näkel', rolle='Multi', standort='Bonn' WHERE id=11;
UPDATE employees SET name='Julius Kawka', rolle='Multi', standort='Bonn' WHERE id=12;
UPDATE employees SET name='Serkan', rolle='Opener', standort=NULL WHERE id=13;
UPDATE employees SET name='Andreas Buharin', rolle='Multi', standort='Bonn' WHERE id=14;
UPDATE employees SET name='Brian Grote', rolle='Multi', standort='Bonn' WHERE id=15;
UPDATE employees SET name='Lyes', rolle='Opener', standort='Bonn' WHERE id=16;
UPDATE employees SET name='Jerry', rolle='Opener', standort='Braunschweig' WHERE id=17;
UPDATE employees SET name='Bruno', rolle='Setter', standort='Braunschweig' WHERE id=18;
UPDATE employees SET name='Marcel', rolle='Opener', standort='Braunschweig' WHERE id=19;
UPDATE employees SET name='Tim', rolle='Opener', standort='Braunschweig' WHERE id=20;
UPDATE employees SET name='Braunschweig', rolle='Opener', standort='Braunschweig' WHERE id=21;
UPDATE employees SET name='Tobias', rolle='NKV-Closer', standort='Bonn' WHERE id=22;
UPDATE employees SET name='Keanu Konsierke', rolle='Multi', standort='Braunschweig' WHERE id=23;
UPDATE employees SET name='Marcel Scheller', rolle='Multi', standort='Braunschweig' WHERE id=24;
UPDATE employees SET name='Bruno Köhl', rolle='Multi', standort='Braunschweig' WHERE id=25;
UPDATE employees SET name='Tim', rolle='Opener', standort='Braunschweig' WHERE id=26;
UPDATE employees SET name='Tim Rempel', rolle='Multi', standort='Braunschweig' WHERE id=27;
UPDATE employees SET name='Jerry Hellemann', rolle='Multi', standort='Braunschweig' WHERE id=28;
UPDATE employees SET name='Christian Martinez-Aguilera', rolle='Multi', standort='Braunschweig' WHERE id=29;
UPDATE employees SET name='Deniz', rolle='Multi', standort='Bonn' WHERE id=31;
UPDATE employees SET name='Dominik Bous', rolle='Multi', standort='Bonn' WHERE id=32;
UPDATE employees SET name='Adrian Röse', rolle='KAM', standort='Braunschweig' WHERE id=33;
UPDATE employees SET name='Thorsten Busch', rolle='KAM', standort='Braunschweig' WHERE id=34;
UPDATE employees SET name='Stefan Morawitz', rolle='KAM', standort='Österreich' WHERE id=35;
UPDATE employees SET name='Sükrü Boydas', rolle='KAM', standort='Österreich' WHERE id=36;
UPDATE employees SET name='Manuel Zimmermann', rolle='KAM', standort='Österreich' WHERE id=37;
UPDATE employees SET name='Dominik Warscha', rolle='KAM', standort='Österreich' WHERE id=38;
UPDATE employees SET name='Lukas Riegler', rolle='KAM', standort='Österreich' WHERE id=39;
UPDATE employees SET name='Arton Mustafa', rolle='KAM', standort='Österreich' WHERE id=40;
UPDATE employees SET name='Matthias Niedermoser', rolle='KAM', standort='Österreich' WHERE id=41;
UPDATE employees SET name='Daniel Saliba', rolle='KAM', standort='Österreich' WHERE id=42;
UPDATE employees SET name='Alexander Korak', rolle='KAM', standort='Österreich' WHERE id=43;
UPDATE employees SET name='Albert Drezgaj', rolle='KAM', standort='Österreich' WHERE id=44;

-- Kündigungen Kontaktdaten (deals_vl)
UPDATE deals_vl SET auslaufend_am='2026-01-16', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1257;
UPDATE deals_vl SET auslaufend_am='2026-02-11', ansprechpartner='Philipp Baumeister, Geschäftsführender Gesellschafter', telefon='498222999288', email_kontakt='philipp.baumeister@robatherm.com', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1272;
UPDATE deals_vl SET auslaufend_am='2026-02-14', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1276;
UPDATE deals_vl SET auslaufend_am='2026-02-17', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1284;
UPDATE deals_vl SET auslaufend_am='2026-02-18', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1286;
UPDATE deals_vl SET auslaufend_am='2026-03-10', ansprechpartner='Claudia Nowoczin, Personalreferentin', telefon='492099515204', email_kontakt='claudia.nowoczin@vta-software.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1313;
UPDATE deals_vl SET auslaufend_am='2026-03-10', ansprechpartner='Claudia Nickel (Recruiting Specialist)', telefon='4915117140853', email_kontakt='claudia.nickel@axians.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1314;
UPDATE deals_vl SET auslaufend_am='2026-03-19', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1322;
UPDATE deals_vl SET auslaufend_am='2026-03-20', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1324;
UPDATE deals_vl SET auslaufend_am='2026-03-25', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1329;
UPDATE deals_vl SET auslaufend_am='2026-03-29', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1333;
UPDATE deals_vl SET auslaufend_am='2026-04-04', ansprechpartner='Herr Dominguez ', telefon='49201851350', email_kontakt='dominguez@hka-essen.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1336;
UPDATE deals_vl SET auslaufend_am='2026-04-08', ansprechpartner='Frank Gniechwitz', telefon='0 177 7347 113', email_kontakt='gniechwitz@gm-gera.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=1341;
UPDATE deals_vl SET auslaufend_am='2026-04-11', ansprechpartner='Beatriz Herrero Nunez', telefon='491743486419', email_kontakt='beatriz.herreronunez@kanadevia-inova.com', weitergeben_an_vertrieb='Ja', neuer_ap_intern='4' WHERE id=1344;
UPDATE deals_vl SET auslaufend_am='2026-06-16', ansprechpartner='Bernd Kamppeter ', telefon='+49 2941 988930', email_kontakt='b.kamppeter@diakonie-lippstadt.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3542;
UPDATE deals_vl SET auslaufend_am='2026-06-15', ansprechpartner='Manuela Zühsdorff', telefon='0 36 35/ 43 43 123', email_kontakt='m.zuehlsdorff@logatec.com', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3543;
UPDATE deals_vl SET auslaufend_am='2026-06-17', ansprechpartner='Tatiana Oliveira', telefon='+49 6322 799 418', email_kontakt='tatiana.oliveira@kst-motorenversuch.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='4' WHERE id=3545;
UPDATE deals_vl SET auslaufend_am='2026-06-22', ansprechpartner='Thomas Borresch', telefon=' 06500 / 917 879', email_kontakt='t.borresch@physiotraining-ruwertal.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3552;
UPDATE deals_vl SET auslaufend_am='2026-04-15', ansprechpartner='Bernd Kamppeter ', telefon='+49 2941 988930', email_kontakt='b.kamppeter@diakonie-lippstadt.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3763;
UPDATE deals_vl SET auslaufend_am='2026-04-18', ansprechpartner='Christoph Hofer', telefon='+  49 7802 70 44 99 - 93', email_kontakt='hofer@jogerst.com', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3768;
UPDATE deals_vl SET auslaufend_am='2026-04-22', ansprechpartner='Marion Prey', telefon='08081 932260', email_kontakt='prey.marion@marienstift-dorfen.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3773;
UPDATE deals_vl SET auslaufend_am='2026-04-22', ansprechpartner='Andreas Kosic', telefon='0711 9237739', email_kontakt='Kosic@pul-ingenieure.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3774;
UPDATE deals_vl SET auslaufend_am='2026-04-24', ansprechpartner='Andreas Neuhauser', telefon='491707846483', email_kontakt='andreas.neuhauser@neuhausergmbh.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3777;
UPDATE deals_vl SET auslaufend_am='2026-05-02', ansprechpartner='Robert Plewnia', telefon='+49 991 9999 2788', email_kontakt='robert.plewnia@he-tga.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='8' WHERE id=3783;
UPDATE deals_vl SET auslaufend_am='2026-05-02', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3785;
UPDATE deals_vl SET auslaufend_am='2026-05-03', ansprechpartner='Patricia Herrmann', telefon='07543 - 93499-11', email_kontakt='patricia.herrmann@hhgeraetebau.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3789;
UPDATE deals_vl SET auslaufend_am='2026-05-07', ansprechpartner='Lina Dierkes', telefon='05642 9874 35', email_kontakt='Lina.Dierkes@kran-betrieb.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3791;
UPDATE deals_vl SET auslaufend_am='2026-05-08', ansprechpartner='Andre Ernst ', telefon='4915127077733', email_kontakt='Andre.Ernst@astral-bi.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3792;
UPDATE deals_vl SET auslaufend_am='2026-05-12', ansprechpartner='Christoph Wiegand', telefon='040-881803-49', email_kontakt='wiegand@wartig-nord.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3799;
UPDATE deals_vl SET auslaufend_am='2026-05-12', ansprechpartner='Stefan Wolfrum ', telefon='09282 98150', email_kontakt='swolfrum@autohaus-wolfrum.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3800;
UPDATE deals_vl SET auslaufend_am='2026-05-20', ansprechpartner='Nico Böhm ', email_kontakt='boehm@vaventus.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='8' WHERE id=3824;
UPDATE deals_vl SET auslaufend_am='2026-05-20', ansprechpartner='Kevin Wagner-Tiefenbach', telefon='+49 03342 249 335 310', email_kontakt='wagner@bsu-sanierungsunion.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='4' WHERE id=3825;
UPDATE deals_vl SET auslaufend_am='2026-05-24', ansprechpartner='Peter Krüger ', telefon='0171 4175567', email_kontakt='Tipkrueger@t-online.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3828;
UPDATE deals_vl SET auslaufend_am='2026-05-27', ansprechpartner='Patrizia Pammer ', email_kontakt='Patricia.Pammer@x-tention.at', weitergeben_an_vertrieb='Ja', neuer_ap_intern='8' WHERE id=3832;
UPDATE deals_vl SET auslaufend_am='2026-05-30', ansprechpartner='Monika Fröhlich', telefon='+49 (0)821 44490-220', email_kontakt='monika.froehlich@sanitaer-kratzer.de', weitergeben_an_vertrieb='Ja', neuer_ap_intern='4' WHERE id=3835;
UPDATE deals_vl SET auslaufend_am='2026-06-06', ansprechpartner='Christian Jacobs', telefon='+49 1632979317', email_kontakt='CJacobs@scheutenglasheiden.com', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3840;
UPDATE deals_vl SET auslaufend_am='2026-06-09', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3842;
UPDATE deals_vl SET auslaufend_am='2026-06-13', weitergeben_an_vertrieb='Ja', neuer_ap_intern='Vertrieb' WHERE id=3847;
