-- Migration 044: VL-Deals Juli 2026 (fach.digital) hinzufügen
-- 26 Datensätze die lokal vorhanden waren, aber in keiner Migration erfasst wurden

DELETE FROM deals_vl WHERE monat='2026-07' AND company_id=1;

INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-11','2026-07',1,4,'sicht-pack Hagner GmbH','Recruiting-Kampagne, Fotoshoot',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-06-25',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-19','2026-07',1,4,'Mager & Wedemeyer Werkzeugmaschinen GmbH','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',5,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-02',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-06','2026-07',1,8,'Standex GmbH','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',2,NULL,NULL,NULL,NULL,NULL,NULL,'2026-07-20',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-13','2026-07',1,8,'x-tention Informationstechnologie GmbH','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',2,NULL,NULL,NULL,NULL,NULL,NULL,'2026-07-27',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-04','2026-07',1,8,'Auto Amthauer GmbH Hanau','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',2,NULL,NULL,NULL,NULL,NULL,NULL,'2026-07-18',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-02','2026-07',1,4,'HOWE Umwelttechnik GmbH','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',2,NULL,NULL,NULL,NULL,NULL,NULL,'2026-07-16',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-09','2026-07',1,33,'Henn GmbH Bauunternehmung','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',2,NULL,NULL,NULL,NULL,NULL,NULL,'2026-07-23',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-09','2026-07',1,33,'Bardowicks.Haus und Holzbau GmbH','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-07-23',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-10','2026-07',1,33,'Autohaus Olenik GmbH','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-07-24',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-10','2026-07',1,33,'Laudon GmbH & Co. KG','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-07-24',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-12','2026-07',1,33,'Graf-Dichtungen GmbH','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-07-26',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-13','2026-07',1,4,'Karl Bachl Hoch – und Tiefbau GmbH & Co. KG','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',2,NULL,NULL,NULL,NULL,NULL,NULL,'2026-07-27',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-19','2026-07',1,6,'EMG Energie-Management GmbH','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',2,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-02',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-19','2026-07',1,6,'Süd-West Touristik','Recruiting-Kampagne',0.0,NULL,NULL,'Offen',2,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-02',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-19','2026-07',1,8,'Veit Höver GmbH & Co. KG',NULL,NULL,NULL,NULL,'Offen',2,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-02',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-27','2026-07',1,8,'Domstadt Autohaus GmbH',NULL,NULL,NULL,NULL,'Offen',2,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-10',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-30','2026-07',1,7,'mosy GmbH','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',2,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-13',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-08','2026-07',1,4,'Alters- und Pflegezentrum Gerbe','RaaS',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-08',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-05','2026-07',1,4,'DOG Deutsche Oelfabrik Gesellschaft für chemische Erzeugnisse mbH & Co. KG','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-07-19',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-20','2026-07',1,4,'T+S Helmrath Logistik GmbH','RaaS',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-20',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-08','2026-07',1,4,'PBS Logitek Deutschland GmbH','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-07-22',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-29','2026-07',1,4,'Heizungs- und Sanitärtechnik Klante GmbH','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-29',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-18','2026-07',1,4,'SPS Klimatechnische Verkaufsu. Beratungs GmbH','RaaS',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-01',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-30','2026-07',1,4,'Rangauklinik Ansbach GmbH','RaaS',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-30',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-28','2026-07',1,4,'IWS GmbH','RaaS',NULL,NULL,NULL,'Offen',1,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-12',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
INSERT INTO deals_vl (datum,monat,company_id,kam_id,kunde,dienstleistung,angebotswert,ae_wert,laufzeit_monate,status,wie_vielt_verlaengerung,kommentar,gewonnen_datum,gewonnen_monat,abgerechnet,kundennummer,gekuendigt_am,auslaufend_am,ansprechpartner,telefon,email_kontakt,upsale_angesprochen,upsale_summe,upsale_angenommen,upsale_angenommen_summe,weitergeben_an_vertrieb,terminiert,neuer_ap_intern) VALUES ('2026-07-25','2026-07',1,4,'GARANT Türen und Zargen GmbH','Recruiting-Kampagne',NULL,NULL,NULL,'Offen',7,NULL,NULL,NULL,NULL,NULL,NULL,'2026-08-08',NULL,NULL,NULL,0,NULL,0,NULL,NULL,0,NULL);
